const auth = require('./auth')
const account = require('./account')
const center=require('./center')
const children=require('./children')
const activity=require('./activity')
const comment=require('./comment')
const like=require('./like')
const donor=require('./donor')
const express = require('express')
const payment=require('./payment')
const router=express.Router()
const notification=require('./notification')
const adropt_detail=require('./adropt_detail')
const proofs=require('./proofs')
const adropt_request=require('./adropt_request')
router.use('/auth',auth)
router.use('/',payment)
router.use('/account',account)
router.use('/center',center)
router.use('/children',children)
router.use('/activity',activity)
router.use('/like',like)
router.use('/comment',comment)
router.use('/donor',donor)
router.use('/notification',notification)
router.use('/adropt_detail',adropt_detail)
router.use('/proofs',proofs)
router.use('/adropt_request',adropt_request)



module.exports = router;